/* 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <iostream>

using namespace std;
#define ulli unsigned long long int
bool isEven(int n){
    return n%2==0;
}
int main(){
    int a=1,b=1,c=2;
    ulli sum=0;
    while(c<4000000){
        c=a+b;
        a=b;
        b=c;
        if(isEven(c)) sum+=c;
    }
    cout<<sum<<endl;
}
//TRY: IMPROVE THE ALGORITHM.